### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by juanitorduz** [red-data-tools/jekyll-jupyter-notebook#1]
Hi!

I am trying to use the  jekyll jupyter notebook extension but I am having some problems! I receive the message:

	The page build failed for the `master` branch with the following error:

	The tag `jupyter_notebook` on line 7 in `index.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

	For information on troubleshooting Jekyll see:

	 https://help.github.com/articles/troubleshooting-jekyll-builds

	If you have any questions you can contact us by replying to this email.

Here is my repository https://github.com/juanitorduz/juanitorduz.github.io

What could be the problem? 

Thanks )
Juan

**Comment by kou** [comment]
GitHub pages doesn't support additional Jekyll plugin. So you can't use this plugin on GitHub pages.
