### ISSUE TITLE
Optionally removing the code inputs from the render

### ISSUE THREAD

**Issue by ashishmathew0297** [red-data-tools/jekyll-jupyter-notebook#12]
I wondered if it would be a good idea to add the option of removing the code inputs in the rendered pdf.

It could probably be something along the lines of the addition of `--no-input ` to the command line. Something like.

```diff
diff --git a/lib/jekyll-jupyter-notebook/converter.rb b/lib/jekyll-jupyter-notebook/converter.rb
index 237500a..ad7e107 100644
--- a/lib/jekyll-jupyter-notebook/converter.rb
+++ b/lib/jekyll-jupyter-notebook/converter.rb
@@ -54,6 +54,7 @@ module JekyllJupyterNotebook
           "--stdout",
         ]
         command_line << "--no-prompt" unless config.fetch("prompt", true)
+        command_line << "--no-input" unless config.fetch("input", true)
         command_line << notebook.path
```

**Comment by kou** [comment]
Could you open a PR with document update https://github.com/red-data-tools/jekyll-jupyter-notebook?tab=readme-ov-file#configurations ?

**Comment by ashishmathew0297** [comment]
Sure! I've opened a PR from my fork with the updates to the readme and the corresponding code change in the `.rb` file.

I'm very new to Ruby, so please let me know if I missed out on anything

**Comment by kou** [comment]
Thanks!
