### ISSUE TITLE
Convert notebook which has latex equations

### ISSUE THREAD

**Issue by m-julian** [red-data-tools/jekyll-jupyter-notebook#14]
Hello,

I am using the [al-folio](https://github.com/alshedivat/al-folio) template, and am trying to input some jupyter notebooks in my webiste. I am having a problem where the latex equations are not being rendered in the final result, I have attached the markdown contents of the example notebook and a picture of the rendered website. I am following the directions given in the [README](https://github.com/red-data-tools/jekyll-jupyter-notebook?tab=readme-ov-file#usage) on how to put the jupyter notebook paths in a markdown post.
```
# Test

This is markdown text with inline equation $E=mc^2$.

This is markdown with equation

$$
E = mc^2
$$
```

Here is the rendered webpage:

<img width="983" alt="image" src="https://github.com/user-attachments/assets/2326bc4e-b84b-4ac4-bb68-0b6525fa65e1">

I am not exactly sure what the issue is. Using `jupyter nbconvert --to html jupyter_notebooks/example.ipynb` converts the notebook successfully and gives the following html rendering:

<img width="762" alt="image" src="https://github.com/user-attachments/assets/d6a9e250-f6b6-475c-84a4-08c90e3f9a42">

Thanks!

**Comment by m-julian** [comment]
Pretty sure the issue is that MathJax is not loaded properly in the iframe, because the following script is loaded in the html file that is in the ``iframe`` tag:

```
<!-- Load mathjax --> 
 <script src="file:///usr/share/javascript/mathjax/MathJax.js?config=TeX-AMS_CHTML-full,Safe"> </script>
```

I am setting up the al-folio website locally with [Docker as in the instructions](https://github.com/alshedivat/al-folio/blob/master/INSTALL.md#local-setup-using-docker-recommended) if that makes a difference.

**Comment by kou** [comment]
Could you provide a test repository that reproduces this case?
I want to try this on my environment.

**Comment by m-julian** [comment]
I've put up an example repo at https://github.com/m-julian/test_equations_jekyll-jupyter-notebook . Running the `docker compose pull` and `docker compose up` should make the website. I've put up the notebook in `/jupyter_notebooks/example.ipynb` and the markdown post at `/_posts/2024-10-06-test.md`.  I've also put up the html that I get with `jupyter nbconvert --to html jupyter_notebooks/example.ipynb` at `/jupyter_notebooks/example.html`.

**Comment by kou** [comment]
Thanks.

.deb changes the MathJax.js URL: https://salsa.debian.org/python-team/packages/nbconvert/-/blob/master/debian/patches/privacy-breaches.patch?ref_type=heads

Could you use non .deb jupyter-nbconvert?

```diff
diff --git a/Dockerfile b/Dockerfile
index 6843d3d..c2d8f5e 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -8,9 +8,10 @@ RUN apt-get update -y && apt-get install -y --no-install-recommends \
     imagemagick \
     build-essential \
     zlib1g-dev \
-    jupyter-nbconvert \
+    pipx \
     inotify-tools procps && \
-    apt-get clean && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
+    apt-get clean && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/* && \
+    PIPX_HOME=/usr/local PIPX_BIN_DIR=/usr/local/bin pipx install nbconvert
 
 
 RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && \
```

**Comment by m-julian** [comment]
@kou thanks, I was able to get it to work, but I had to add `PIPX_HOME=/usr/local PIPX_BIN_DIR=/usr/local/bin pipx install jupyter --include-deps` instead. Otherwise it complains that it cannot find jupyter, I assume that happens here:

https://github.com/red-data-tools/jekyll-jupyter-notebook/blob/a4e3e904755f0761e9bde0c823e47016d0fb8221/lib/jekyll-jupyter-notebook/converter.rb#L50-L54

I then did `docker compose build --no-cache` and `docker compose up`. After this, it seems to work. This is what I get now:

<img width="951" alt="image" src="https://github.com/user-attachments/assets/8d294cb4-bf5b-41b5-94ed-a503d2e06eea">

If I run it with the original command `PIPX_HOME=/usr/local PIPX_BIN_DIR=/usr/local/bin pipx install nbconvent` , then I get 

```
jekyll-1  |   Conversion error: JekyllJupyterNotebook::Converter encountered an error while converting 'jupyter_notebooks/example.ipynb':
jekyll-1  |                     No such file or directory - jupyter
jekyll-1  | /usr/local/bundle/gems/jekyll-jupyter-notebook-0.0.6/lib/jekyll-jupyter-notebook/converter.rb:58:in `spawn': No such file or directory - jupyter (Errno::ENOENT)
```

I think this might be because of how pipx installs nbconvert, but I am not too familiar with pipx, so not sure.

**Comment by kou** [comment]
Ah, sorry. You're right. Or we can install only `jupyter-core` and `nbconvert`:

```bash
PIPX_HOME=/usr/local PIPX_BIN_DIR=/usr/local/bin pipx install jupyter-core && \
PIPX_HOME=/usr/local PIPX_BIN_DIR=/usr/local/bin pipx install nbconvert
```

Can we close this?

**Comment by m-julian** [comment]
Yes, I think the issue is solved now, appreciate the help! I'll create an issue/pull request in the al-folio repo for this.
