### ISSUE TITLE
Plugin doesn't work in collections.

### ISSUE THREAD

**Issue by jlconlin** [red-data-tools/jekyll-jupyter-notebook#8]
I tried to use this plugin to convert Jupyter notebooks contained in a Jekyll collection. It didn't even try to do the conversion and I kept getting the error `ERROR '/mycollection/example.ipynb.html' not found`. The file `/mycollection/example.ipynb` was there, it was just never converted to an html file. 

When I moved `example.ipynb` outside of `mycollection` then it was found and converted.

**Comment by kou** [comment]
Could you provide a sample Jekyll project that reproduces this case?

**Comment by jlconlin** [comment]
I was able to replicate this using the example that comes with the repository. I forked the repository into my own space and created a `collections` branch. You can access it here: https://github.com/jlconlin/jekyll-jupyter-notebook/tree/collections

After doing `bundle exec jekyll serve` you can navigate to https://localhost:4000/mycollection and you will see the issue.

**Comment by kou** [comment]
Thanks. I've added support for collection.

**Comment by jlconlin** [comment]
Thanks, @kou. I can confirm that this works in my site as well. I did have to specify the full path to the git repository in my Gemfile. Seems it perhaps hasn't propagated to ruby gems yet.

**Comment by jlconlin** [comment]
Thanks, @kou. I can confirm that this works in my site as well. I did have to specify the full path to the git repository in my Gemfile. Seems it perhaps hasn't propagated to ruby gems yet.

**Comment by kou** [comment]
Really?
New version has been published: https://rubygems.org/gems/jekyll-jupyter-notebook
